'*.{cjs,js,json,jsx,mjs,ts,tsx,yaml,yml}':
  - eslint --fix
  - prettier --write
'*.ps1':
  - uv run .scripts/pwshlint.py --fix
'*.py':
  - uv run pylint
  - uv run ruff format
'*.sh':
  - python .scripts/shlint.py --fix
